require("config.functions.format_sql_keywords")
require("config.functions.telescope_git_or_find_files")
require("config.functions.redo_migrations")
require("config.functions.strip_trailing_whitespace")
require("config.functions.resolve_db_conflict")
